# Generated by Django 3.1.1 on 2020-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201111_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='users',
        ),
        migrations.AddField(
            model_name='manageruser',
            name='plans',
            field=models.ManyToManyField(through='api.Subscription', to='api.Plan'),
        ),
    ]
